# fly.toml app configuration file generated for lucius-v on 2023-07-17T14:17:14+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "lucius-v"
primary_region = "ams"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[mounts]
source="lucius_v_database"
destination="/db"
